package bridge

enum class ErrorType(val errorMessage: String) {
    LENGTH(ERROR.format(ERROR_NUMBER_RANGE_MESSAGE)),
    NUMBER(ERROR.format(ERROR_NUMBER_MESSAGE)),
    EMPTY(ERROR.format(ERROR_EMPTY_MESSAGE)),
    DIRECTION_LETTER(ERROR.format(ERROR_DRIECTION_LETTER_MESSAGE)),
    DIRECTION_UPPER(ERROR.format(ERROR_DRIECTION_UPPER_MESSAGE)),
    DIRECTION_LENGTH(ERROR.format(ERROR_DRIECTION_LENGTH_MESSAGE)),
    DIRECTION(ERROR.format(ERROR_DRIECTION_MESSAGE)),
    COMMAND_LETTER(ERROR.format(ERROR_COMMAND_LETTER_MESSAGE)),
    COMMAND_UPPER(ERROR.format(ERROR_COMMAND_UPPER_MESSAGE))
}